# Macro file for the initialization of example FastSimChannelingRad
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
#Geometry setting
/control/execute geom.mac
#
#Initialize kernel
/run/initialize
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
