#
# macro file for test58.cc
#
/control/verbose 2
/run/verbose 2
#/tracking/verbose 1
#
/testem/det/setAbsMat   G4_Si
/testem/det/setAbsThick 1e-6 cm
/testem/det/setAbsYZ    1 cm
#
/testem/phys/setTh 21 eV
#/testem/phys/setXSecModel precise
#
/testem/phys/addPhysics  standardISS
#
/run/setCut 1e-5 mm
#/run/setCutForAGivenParticle e- 1e-5 mm
#
/run/initialize
#
#/testem/gun/setDefault
/gun/particle e-
############## Alpha
#/gun/lepton electron
#
#
#
/gun/energy  10 MeV 
/testem/stack/killSecondaries
/run/beamOn 100


