FNAME        = test46
getenv       = true
executable   = $ENV(G4INSTALL)/tests/ctests_integration/test46/run.csh
ID           = $(ClusterId).$(ProcId)
output       = $ENV(VFEM)/test46/$ENV(REFERENCE)/$(FNAME).$(ID).out
error        = $ENV(VFEM)/test46/$ENV(REFERENCE)/$(FNAME).$(ID).err
log          = $ENV(VFEM)/test46/$ENV(REFERENCE)/$(FNAME).$(ID).log
request_cpus = 1
requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour  = "workday"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue
