/vis/open ! 800x800-0+0

/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 60 30
/vis/drawVolume Cell

/vis/scene/add/axes 0 0 0 10 um
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true

/vis/viewer/set/autoRefresh true

/vis/enable
/vis/viewer/flush