//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * The  Geant4 software  is  copyright of the Copyright Holders  of *
// * the Geant4 Collaboration.  It is provided  under  the terms  and *
// * conditions of the Geant4 Software License,  included in the file *
// * LICENSE and available at  http://cern.ch/geant4/license .  These *
// * include a list of copyright holders.                             *
// *                                                                  *
// * Neither the authors of this software system, nor their employing *
// * institutes,nor the agencies providing financial support for this *
// * work  make  any representation or  warranty, express or implied, *
// * regarding  this  software system or assume any liability for its *
// * use.  Please see the license in the file  LICENSE  and URL above *
// * for the full disclaimer and the limitation of liability.         *
// *                                                                  *
// * This  code  implementation is the result of  the  scientific and *
// * technical work of the GEANT4 collaboration.                      *
// * By using,  copying,  modifying or  distributing the software (or *
// * any work based  on the software)  you  agree  to acknowledge its *
// * use  in  resulting  scientific  publications,  and indicate your *
// * acceptance of all terms of the Geant4 Software license.          *
// ********************************************************************
//
//---------------------------------------------------------------------------//
// Unit test for G4SPSRandomGenerator
// Initial implementation generated by GitHub CoPilot (GPT-4.1)
//---------------------------------------------------------------------------//
#include "G4SPSRandomGenerator.hh"

#include "G4FixedRandomEngine.hh"
#include "G4ThreeVector.hh"

#include "CLHEP/Random/Random.h"
#include <gtest/gtest.h>

#include <vector>

//---------------------------------------------------------------------------//
// TEST FIXTURES
//---------------------------------------------------------------------------//
namespace
{
// Constant for precision with which to compare double numbers
constexpr G4double kPrecision = 1e-12;

// Bias Histogram Creation Functions
//---------------------------------------------------------------------------//
// Uniform bias: all bins have the same weight
std::vector<G4ThreeVector> UniformBias(size_t n_bins, double weight)
{
  std::vector<G4ThreeVector> bias;
  double step = 1.0 / n_bins;
  bias.emplace_back(0.0, 0.0, 0.0);  // lower edge, ignored
  for (size_t i = 1; i <= n_bins; ++i)
  {
    bias.emplace_back(i * step, weight, 0.0);
  }
  return bias;
}

//---------------------------------------------------------------------------//
// Helper for calculating expected rndm and weights
// This is a little circular as this essentially does what the GenRand functions
// do, albeit with a different implementation. The current need for this is
// checking reproducibility whilst refactoring, so this is acceptable for now.
// It also requires manual calculation of the CDF and weights vector.
struct G4SPSExpectedCalculator
{
    double expected_weight(double rndm) const
    {
      for (const auto& bin : weights_)
      {
        if (rndm < bin.x()) return bin.y();
      }
      return -1.0;
    }

    double expected_rndm(double known_rndm) const
    {
      // 1. Find bin of cdf in which known_rndm lies (y_lower, y_upper)
      auto bin = std::find_if(cdf_.begin(), cdf_.end(), [&known_rndm](const auto& cdf_bin) {
        return known_rndm < cdf_bin.y();
      });

      // Return "impossible" rndm if out of range.
      if (bin == cdf_.end()) return -1.0;

      // Linear interpolate back to x
      G4double x_upper = (*bin).x();
      G4double y_upper = (*bin).y();
      G4double x_lower = 0.0;
      G4double y_lower = 0.0;
      if (bin != cdf_.begin())
      {
        auto lower = (bin - 1);
        x_lower = (*lower).x();
        y_lower = (*lower).y();
      }

      return x_lower + (x_upper - x_lower) * (known_rndm - y_lower) / (y_upper - y_lower);
    };

    // Lambda-ize expected_weight for use in fixtures
    auto expected_weight_fn() const
    {
      return [this](G4double r) {
        return this->expected_weight(r);
      };
    }

    // Lambda-ize expected_rndm for use in fixtures
    auto expected_rndm_fn() const
    {
      return [this](G4double r) {
        return this->expected_rndm(r);
      };
    }

    const std::vector<G4ThreeVector>& cdf_;
    const std::vector<G4ThreeVector>& weights_;
};

// Parameter type for tests to allow forwarding to relevant SetBias/GenRand
// functions for each "axis" of the generator (X, Y, Z, Theta, Phi, Energy, PosTheta, PosPhi)
struct G4SPSBiasAxis
{
    std::function<void(G4SPSRandomGenerator&, const G4ThreeVector&)> SetBias;
    std::function<double(G4SPSRandomGenerator&)> GenRand;
    G4String name;
};

// Test Fixture to encapsulate fixed random sequence and common testing algorithm
class G4SPSRandomGeneratorTest : public ::testing::TestWithParam<G4SPSBiasAxis>
{
  protected:

    void SetUp() override
    {
      // Initialize with N random numbers uniformly increasing from 0 to 1
      const size_t length = 100;
      const double step = 1.0 / length;
      mock_rndm.reserve(length);
      for (size_t i = 0; i < length; ++i)
      {
        // At present, biasing breaks for a true-zero RN...
        mock_rndm.push_back((i + 0.5) * step);
      }

      // Install fixed sequence in CLHEP Engine used in Geant4
      engine = new G4FixedRandomEngine(mock_rndm);
      CLHEP::HepRandom::setTheEngine(engine);
    }

    void TearDown() override { delete engine; }

    void RunOver(const std::vector<G4ThreeVector>& bias,
                 std::function<G4double(G4double)> expected_rndm,
                 std::function<G4double(G4double)> expected_weight)
    {
      const auto& axis = GetParam();

      // Fill weights
      for (const auto& bp : bias)
      {
        axis.SetBias(sps, bp);
      }

      // Compare actual/expected
      for (const auto& input_rndm : mock_rndm)
      {
        SCOPED_TRACE(G4String("input_rndm evaluates to ") + std::to_string(input_rndm));
        double actual_rndm = axis.GenRand(sps);
        EXPECT_NEAR(actual_rndm, expected_rndm(input_rndm), kPrecision);
        EXPECT_NEAR(sps.GetBiasWeight(), expected_weight(actual_rndm), kPrecision);
      }
    }

    std::vector<double> mock_rndm;
    G4FixedRandomEngine* engine = nullptr;
    G4SPSRandomGenerator sps;
};

}  // namespace

//---------------------------------------------------------------------------//
// TESTS
//---------------------------------------------------------------------------//
TEST_P(G4SPSRandomGeneratorTest, UnbiasedOutputRange)
{
  // Without biasing, must get passthrough with no modification and exact numbers
  const auto& axis = GetParam();
  for (const auto& input_rndm : mock_rndm)
  {
    double actual_rndm = axis.GenRand(sps);
    EXPECT_EQ(actual_rndm, input_rndm);
    EXPECT_EQ(sps.GetBiasWeight(), 1.0);
  }
}

TEST_P(G4SPSRandomGeneratorTest, UniformBiasOutputRange)
{
  // Uniform bias is effectively passthrough and should not
  // modify weights other than FP rounding within precision
  auto bias = UniformBias(13, 1.365);
  auto expected_rndm = [](G4double r) {
    return r;
  };
  auto expected_weight = [](G4double) {
    return 1.0;
  };

  SCOPED_TRACE(::testing::UnitTest::GetInstance()->current_test_info()->name());
  this->RunOver(bias, expected_rndm, expected_weight);
}

TEST_P(G4SPSRandomGeneratorTest, SingleBinBiasOutputRange)
{
  // Single bin bias basically compresses rngs to bin low-high edge
  // Weight is binwidth
  // Take 12 uniform bins with bin 5 as the single filled one (arbitrary weight)
  // - Bin low edge = 1./12.*5
  // - Bin width reduces to bin width for single bin = 1./12.
  const size_t n_bins = 12;
  const size_t selected_bin = 5;
  const G4double selected_bin_width = 1.0 / n_bins;
  const G4double selected_bin_low_edge = selected_bin * selected_bin_width;

  const G4double expected_bin_weight = selected_bin_width;
  const G4double selected_weight = 0.3654;

  // We create two points (single bin) as the non-zero elements are not needed here
  auto bias = std::vector<G4ThreeVector>{
    {selected_bin_low_edge, 0.0}, {selected_bin_low_edge + selected_bin_width, selected_weight}};

  auto expected_weight = [&](G4double) {
    return expected_bin_weight;
  };
  auto expected_rndm = [&](G4double r) {
    return selected_bin_low_edge + selected_bin_width * r;
  };

  SCOPED_TRACE(::testing::UnitTest::GetInstance()->current_test_info()->name());
  this->RunOver(bias, expected_rndm, expected_weight);
}

TEST_P(G4SPSRandomGeneratorTest, VaryingBiasFixedBinsOutputRange)
{
  // Mock a Gaussian-like function
  // - 5 bins, weight peaking in 3rd (central) bin
  // We need to include the low edge!
  const std::vector<G4ThreeVector> bias = {{0.0, 0.0}, {0.2, 1.0}, {0.4, 2.0},
                                           {0.6, 4.0}, {0.8, 2.0}, {1.0, 1.0}};
  // Total area is 10, so CDF is:
  const std::vector<G4ThreeVector> cdf = {
    {0.2, 0.1}, {0.4, 0.3}, {0.6, 0.7}, {0.8, 0.9}, {1.0, 1.0}};
  // For a rndm falling in bin i of CDF, expected weight is binWidth(i)/NORM{biasH(i)} so:
  const std::vector<G4ThreeVector> weights = {
    {0.2, 0.2 / 0.1}, {0.4, 0.2 / 0.2}, {0.6, 0.2 / 0.4}, {0.8, 0.2 / 0.2}, {1.0, 0.2 / 0.1}};

  G4SPSExpectedCalculator ec{cdf, weights};

  SCOPED_TRACE(::testing::UnitTest::GetInstance()->current_test_info()->name());
  this->RunOver(bias, ec.expected_rndm_fn(), ec.expected_weight_fn());
}

TEST_P(G4SPSRandomGeneratorTest, VaryingBiasVaryingBinsOutputRange)
{
  // Mock a skew Gaussian-like function
  // - 5 bins, weight peaking in 4th bin
  // - non-constant bin width
  // We need to include the low edge!
  const std::vector<G4ThreeVector> bias = {{0.0, 0.0}, {0.1, 1.0}, {0.4, 2.0},
                                           {0.7, 3.0}, {0.8, 4.0}, {1.0, 1.0}};
  // Total area is 11, so CDF is:
  const std::vector<G4ThreeVector> cdf = {
    {0.1, 1. / 11.}, {0.4, 3. / 11.}, {0.7, 6. / 11.}, {0.8, 10. / 11.}, {1.0, 11. / 11.}};
  // For a rndm falling in bin i of cdfH, expected weight is binWidth(i)/NORM{biasH(i)} so:
  const std::vector<G4ThreeVector> weights = {{0.1, 0.1 / (1. / 11.)},
                                              {0.4, 0.3 / (2. / 11.)},
                                              {0.7, 0.3 / (3. / 11.)},
                                              {0.8, 0.1 / (4. / 11.)},
                                              {1.0, 0.2 / (1. / 11.)}};

  G4SPSExpectedCalculator ec{cdf, weights};

  SCOPED_TRACE(::testing::UnitTest::GetInstance()->current_test_info()->name());
  this->RunOver(bias, ec.expected_rndm_fn(), ec.expected_weight_fn());
}

//---------------------------------------------------------------------------//
// Instantiate tests over each "axis" supported by G4SPSRandomGenerator
//---------------------------------------------------------------------------//
INSTANTIATE_TEST_SUITE_P(
  Axes, G4SPSRandomGeneratorTest,
  ::testing::Values(
    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetXBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandX(); }, "GenRandX"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetYBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandY(); }, "GenRandY"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetZBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandZ(); }, "GenRandZ"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetThetaBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandTheta(); }, "GenRandTheta"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetPhiBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandPhi(); }, "GenRandPhi"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetEnergyBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandEnergy(); }, "GenRandEnergy"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetPosThetaBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandPosTheta(); }, "GenRandPosTheta"},

    G4SPSBiasAxis{[](G4SPSRandomGenerator& r, const G4ThreeVector& v) { r.SetPosPhiBias(v); },
                  [](G4SPSRandomGenerator& r) { return r.GenRandPosPhi(); }, "GenPosPhiEnergy"}
    // Add more as needed
    ),
  [](const testing::TestParamInfo<G4SPSRandomGeneratorTest::ParamType>& param_info) {
    // Can use param_info.param here to generate the test suffix
    return param_info.param.name;
  });

//---------------------------------------------------------------------------//
// TODO (Maybe): Tests of biasing on N>1 axis at same time
// - Not clear how common this is, generally up to client of G4SPSRandomGenerator
//   to know and handle this correctly
//---------------------------------------------------------------------------//
