static char const *protareTemplateChars = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<reactionSuite projectile=\"PROJECTILE_ID\" target=\"TARGET_ID\" evaluation=\"Emptyish\" format=\"2.0\" projectileFrame=\"lab\" interaction=\"INTERACTION\">\n"
"  <styles>\n"
"    <evaluated label=\"eval\" library=\"Emptyish\" version=\"1.0\">\n"
"     <temperature value=\"0\" unit=\"K\"/>\n"
"     <projectileEnergyDomain min=\"1e-11\" max=\"30\" unit=\"MeV\"/></evaluated>\n"
"   <averageProductData label=\"apd\" derivedFrom=\"eval\"/>\n"
"   <MonteCarlo_cdf label=\"MonteCarlo_cdf\" derivedFrom=\"apd\"/>\n"
"   <heated label=\"heated_000\" derivedFrom=\"MonteCarlo_cdf\">\n"
"     <temperature value=\"0\" unit=\"MeV/k\"/></heated>\n"
"   <griddedCrossSection label=\"MonteCarlo_000\" derivedFrom=\"heated_000\">\n"
"     <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"points\">\n"
"       <values>1e-11 30</values></grid></griddedCrossSection>\n"
"   <heatedMultiGroup label=\"MultiGroup_000\" derivedFrom=\"heated_000\">\n"
"     <transportables>\n"
"       <transportable label=\"PROJECTILE_ID\" conserve=\"number\">\n"
"         <group label=\"UNKNOWN_1\">\n"
"           <grid index=\"0\" label=\"energy\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid></group></transportable>\n"
"       <transportable label=\"TARGET_ID\" conserve=\"number\">\n"
"         <group label=\"UNKNOWN_2\">\n"
"           <grid index=\"0\" label=\"energy\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>TARGET_MULTIGROUP_BOUNDARIES</values></grid></group></transportable></transportables>\n"
"     <flux label=\"LLNL_fid_1\">\n"
"       <XYs2d>\n"
"         <axes>\n"
"           <axis index=\"2\" label=\"energy_in\" unit=\"MeV\"/>\n"
"           <axis index=\"1\" label=\"mu\" unit=\"\"/>\n"
"           <axis index=\"0\" label=\"flux\" unit=\"1/s\"/></axes>\n"
"         <function1ds>\n"
"           <Legendre outerDomainValue=\"0\"><values>85</values></Legendre>\n"
"           <Legendre outerDomainValue=\"2e2\"><values>85</values></Legendre></function1ds></XYs2d></flux>\n"
"     <inverseSpeed>\n"
"       <gridded1d>\n"
"         <axes>\n"
"           <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"           <axis index=\"0\" label=\"inverse speed\" unit=\"mus/m\"/></axes>\n"
"         <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"           <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"           <values valueType=\"Integer32\" label=\"lengths\">PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS</values>\n"
"           <values>INVERSE_SPEEDS</values></array></gridded1d></inverseSpeed></heatedMultiGroup></styles>\n"
" <PoPs name=\"protare_internal\" version=\"1.0\" format=\"2.0\">\n"
"   <unorthodoxes>\n"
"   <unorthodox id=\"PROJECTILE_ID\">\n"
"     <mass>\n"
"       <double label=\"eval\" value=\"PROJECTILE_MASS\" unit=\"amu\"/></mass></unorthodox>\n"
"   <unorthodox id=\"TARGET_ID\">\n"
"     <mass>\n"
"       <double label=\"eval\" value=\"TARGET_MASS\" unit=\"amu\"/></mass></unorthodox></unorthodoxes></PoPs>\n"
" <reactions>\n"
"   <reaction label=\"REACTION_LABEL\" ENDF_MT=\"2\">\n"
"     <crossSection>\n"
"       <XYs1d label=\"eval\">\n"
"         <axes>\n"
"           <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"           <axis index=\"0\" label=\"crossSection\" unit=\"b\"/></axes>\n"
"         <values>\n"
"           1e-11 CROSSSECTION_VALUE 30 CROSSSECTION_VALUE</values></XYs1d>\n"
"       <XYs1d label=\"heated_000\">\n"
"         <axes>\n"
"           <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"           <axis index=\"0\" label=\"crossSection\" unit=\"b\"/></axes>\n"
"         <values>\n"
"           1e-11 CROSSSECTION_VALUE 30 CROSSSECTION_VALUE</values></XYs1d>\n"
"       <Ys1d label=\"MonteCarlo_000\">\n"
"         <axes>\n"
"           <grid index=\"1\" href=\"/reactionSuite/styles/griddedCrossSection[@label='MonteCarlo_000']/grid[@index='1']\"/>\n"
"           <axis index=\"0\" label=\"crossSection\" unit=\"b\"/></axes>\n"
"         <values>CROSSSECTION_VALUE CROSSSECTION_VALUE</values></Ys1d>\n"
"       <gridded1d label=\"MultiGroup_000\">\n"
"         <axes>\n"
"           <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"           <axis index=\"0\" label=\"crossSection\" unit=\"b\"/></axes>\n"
"         <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"           <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"           <values valueType=\"Integer32\" label=\"lengths\">PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS</values>\n"
"           <values>CROSSSECTION_MULTIGROUP_DATA</values></array></gridded1d></crossSection>\n"
"     <outputChannel genre=\"twoBody\">\n"
"       <Q>\n"
"         <constant1d label=\"eval\" value=\"0\" domainMin=\"1e-11\" domainMax=\"30\">\n"
"           <axes>\n"
"             <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"             <axis index=\"0\" label=\"Q\" unit=\"MeV\"/></axes></constant1d>\n"
"         <gridded1d label=\"MultiGroup_000\">\n"
"           <axes>\n"
"             <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"               <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"             <axis index=\"0\" label=\"Q * crossSection\" unit=\"MeV * b\"/></axes>\n"
"           <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"             <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"             <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"             <values/></array></gridded1d></Q>\n"
"       <products>\n"
"         <product pid=\"PROJECTILE_ID\" label=\"PROJECTILE_ID\">\n"
"           <multiplicity>\n"
"             <XYs1d label=\"eval\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"multiplicity\" unit=\"\"/></axes>\n"
"               <values>1e-11 1 30 1</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"multiplicity * crossSection\" unit=\"b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS</values>\n"
"                 <values>MULTIGROUP_MULTIPLICITY</values></array></gridded1d></multiplicity>\n"
"           <distribution>\n"
"             <angularTwoBody label=\"eval\" productFrame=\"centerOfMass\">\n"
"               <XYs2d>\n"
"                 <axes>\n"
"                   <axis index=\"2\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                   <axis index=\"1\" label=\"mu\" unit=\"\"/>\n"
"                   <axis index=\"0\" label=\"P(mu|energy_in)\" unit=\"\"/></axes>\n"
"                 <function1ds>\n"
"                   <XYs1d outerDomainValue=\"1e-11\"><values>-1 0.5 1 0.5</values></XYs1d>\n"
"                   <XYs1d outerDomainValue=\"30\"><values>-1 0.5 1 0.5</values></XYs1d></function1ds></XYs2d></angularTwoBody>\n"
"             <angularTwoBody label=\"MonteCarlo_cdf\" productFrame=\"centerOfMass\">\n"
"               <XYs2d>\n"
"                 <axes>\n"
"                   <axis index=\"2\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                   <axis index=\"1\" label=\"mu\" unit=\"\"/>\n"
"                   <axis index=\"0\" label=\"P(mu|energy_in)\" unit=\"\"/></axes>\n"
"                 <function1ds>\n"
"                   <xs_pdf_cdf1d outerDomainValue=\"1e-11\"><xs><values>-1 1</values></xs><pdf><values>0.5 0.5</values></pdf><cdf><values>0 1</values></cdf></xs_pdf_cdf1d>\n"
"                   <xs_pdf_cdf1d outerDomainValue=\"30\"><xs><values>-1 1</values></xs><pdf><values>0.5 0.5</values></pdf><cdf><values>0 1</values></cdf></xs_pdf_cdf1d></function1ds></XYs2d></angularTwoBody></distribution>\n"
"           <averageProductEnergy>\n"
"             <XYs1d label=\"apd\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"averageProductEnergy\" unit=\"MeV\"/></axes>\n"
"               <values>1e-11 0 30 0</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"averageProductEnergy * crossSection\" unit=\"MeV * b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"                 <values/></array></gridded1d></averageProductEnergy>\n"
"           <averageProductMomentum>\n"
"             <XYs1d label=\"apd\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"averageProductMomentum\" unit=\"MeV/c\"/></axes>\n"
"               <values>1e-11 0 30 0</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"averageProductMomentum * crossSection\" unit=\"MeV/c * b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"                 <values/></array></gridded1d></averageProductMomentum></product>\n"
"         <product pid=\"TARGET_ID\" label=\"TARGET_ID\">\n"
"           <multiplicity>\n"
"             <XYs1d label=\"eval\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"multiplicity\" unit=\"\"/></axes>\n"
"               <values>1e-11 1 30 1</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"multiplicity * crossSection\" unit=\"b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS</values>\n"
"                 <values>MULTIGROUP_MULTIPLICITY</values></array></gridded1d></multiplicity>\n"
"           <distribution>\n"
"             <angularTwoBody label=\"eval\" productFrame=\"centerOfMass\">\n"
"               <recoil href=\"/reactionSuite/reactions/reaction[@label='emptyish']/outputChannel/products/product[@label='n']/distribution/angularTwoBody[@label='eval']\"/></angularTwoBody></distribution>\n"
"           <averageProductEnergy>\n"
"             <XYs1d label=\"apd\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"averageProductEnergy\" unit=\"MeV\"/></axes>\n"
"               <values>1e-11 0 30 0</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"averageProductEnergy * crossSection\" unit=\"MeV * b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"                 <values/></array></gridded1d></averageProductEnergy>\n"
"           <averageProductMomentum>\n"
"             <XYs1d label=\"apd\">\n"
"               <axes>\n"
"                 <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"                 <axis index=\"0\" label=\"averageProductMomentum\" unit=\"MeV/c\"/></axes>\n"
"               <values>1e-11 0 30 0</values></XYs1d>\n"
"             <gridded1d label=\"MultiGroup_000\">\n"
"               <axes>\n"
"                 <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"                   <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"                 <axis index=\"0\" label=\"averageProductMomentum * crossSection\" unit=\"MeV/c * b\"/></axes>\n"
"               <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"                 <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"                 <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"                 <values/></array></gridded1d></averageProductMomentum></product></products></outputChannel>\n"
"     <availableEnergy>\n"
"       <XYs1d label=\"apd\">\n"
"         <axes>\n"
"           <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"           <axis index=\"0\" label=\"energy_available\" unit=\"MeV\"/></axes>\n"
"         <values>1e-11 1e-11 30 30</values></XYs1d>\n"
"       <gridded1d label=\"MultiGroup_000\">\n"
"         <axes>\n"
"           <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"           <axis index=\"0\" label=\"energy_available * crossSection\" unit=\"MeV * b\"/></axes>\n"
"         <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"           <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"           <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"           <values/></array></gridded1d></availableEnergy>\n"
"     <availableMomentum>\n"
"       <XYs1d label=\"apd\">\n"
"         <axes>\n"
"           <axis index=\"1\" label=\"energy_in\" unit=\"MeV\"/>\n"
"            <axis index=\"0\" label=\"momentum_available\" unit=\"MeV/c\"/></axes>\n"
"          <values>1e-11 0 30 0</values></XYs1d>\n"
"       <gridded1d label=\"MultiGroup_000\">\n"
"         <axes>\n"
"           <grid index=\"1\" label=\"energy_in\" unit=\"MeV\" style=\"boundaries\">\n"
"             <values>PROJECTILE_MULTIGROUP_BOUNDARIES</values></grid>\n"
"           <axis index=\"0\" label=\"momentum_available * crossSection\" unit=\"MeV/c * b\"/></axes>\n"
"         <array shape=\"PROJECTILE_MULTIGROUP_NUMBER_OF_GROUPS\" compression=\"flattened\">\n"
"           <values valueType=\"Integer32\" label=\"starts\">0</values>\n"
"            <values valueType=\"Integer32\" label=\"lengths\">0</values>\n"
"            <values/></array></gridded1d></availableMomentum></reaction></reactions>\n"
"</reactionSuite>\n";
