#================================================
#     Macro file for hadr01
#     06.06.2006 V.Ivanchneko
#================================================
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
#
/testhadr/TargetMat        G4_PbWO4
/testhadr/targetElm        Pb
/testhadr/TargetRadius     1  cm
/testhadr/TargetLength     10 cm
/run/printProgress         10
#
/run/initialize
/process/em/workerVerbose 0
#
/gun/particle alpha
/gun/energy 100. MeV
#/testhadr/fileName  gnuc
/testhadr/particle alpha
/testhadr/verbose 1
/process/eLoss/verbose 0
/run/beamOn 1
#
