/control/verbose 2
/run/verbose 1
#
/gun/particle ion
/gun/ion 91 234 0 103.42
#
/rdecay01/fullChain true
#
/tracking/verbose 2
/run/beamOn 1
#
/control/cout/ignoreThreadsExcept 0
/analysis/setFileName it3
/analysis/h1/set 3  100  0. 1000 keV #gamma
/analysis/h1/set 4  100  5. 15   MeV #alpha
#
/tracking/verbose 0
/run/printProgress 1000
#  
#/run/beamOn 38578
#/run/beamOn 2727
/run/beamOn 100000
#/tracking/verbose 2
#/run/beamOn 1
