FNAME        = test37
getenv       = true
executable   = $ENV(G4BWORK)/$(FNAME)
ID           = $(ClusterId).$(ProcId)
output       = $(name1)_$(phys).$(ID).out
error        = $(name1)_$(phys).$(ID).err
log          = $(FNAME)_$(name1)_$(phys).$(ID).log
request_cpus = 1
requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour = "workday"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_remaps = "Sandia.out=$(name1)_$(phys)$(name2)"
arguments = $ENV(G4INSTALL)/tests/ctests_integration/$(FNAME)/$(argum).in

environment = "PHYSLIST=emstandard_$(phys)"

queue phys, argum, name1, name2 from (
opt0, Aluminum, Al, .log
opt0, Molybdenum, Mo, .log
opt0, Tantalum, Ta, .log
opt0, TaAl, TaAl, .log
opt0, AlAuAl, AlAuAl, .log
opt0, Beryllium, Be, .log
opt0, Uranium, U, .log
opt0, Silicon_15keV, Si, _15keV.log
opt0, Silicon_20keV, Si, _20keV.log
opt0, Silicon_30keV, Si, _30keV.log
opt0, Silicon_40keV, Si, _40keV.log
opt0, Silicon_50keV, Si, _50keV.log
opt3, Aluminum, Al, .log
opt3, Molybdenum, Mo, .log
opt3, Tantalum, Ta, .log
opt3, TaAl, TaAl, .log
opt3, AlAuAl, AlAuAl, .log
opt3, Beryllium, Be, .log
opt3, Uranium, U, .log
opt3, Silicon_15keV, Si, _15keV.log
opt3, Silicon_20keV, Si, _20keV.log
opt3, Silicon_30keV, Si, _30keV.log
opt3, Silicon_40keV, Si, _40keV.log
opt3, Silicon_50keV, Si, _50keV.log
opt4, Aluminum, Al, .log
opt4, Molybdenum, Mo, .log
opt4, Tantalum, Ta, .log
opt4, TaAl, TaAl, .log
opt4, AlAuAl, AlAuAl, .log
opt4, Beryllium, Be, .log
opt4, Uranium, U, .log
opt4, Silicon_15keV, Si, _15keV.log
opt4, Silicon_20keV, Si, _20keV.log
opt4, Silicon_30keV, Si, _30keV.log
opt4, Silicon_40keV, Si, _40keV.log
opt4, Silicon_50keV, Si, _50keV.log
optG, Aluminum, Al, .log
optG, Molybdenum, Mo, .log
optG, Tantalum, Ta, .log
optG, TaAl, TaAl, .log
optG, AlAuAl, AlAuAl, .log
optG, Beryllium, Be, .log
optG, Uranium, U, .log
optG, Silicon_15keV, Si, _15keV.log
optG, Silicon_20keV, Si, _20keV.log
optG, Silicon_30keV, Si, _30keV.log
optG, Silicon_40keV, Si, _40keV.log
optG, Silicon_50keV, Si, _50keV.log
optS, Aluminum, Al, .log
optS, Molybdenum, Mo, .log
optS, Tantalum, Ta, .log
optS, TaAl, TaAl, .log
optS, AlAuAl, AlAuAl, .log
optS, Beryllium, Be, .log
optS, Uranium, U, .log
optS, Silicon_15keV, Si, _15keV.log
optS, Silicon_20keV, Si, _20keV.log
optS, Silicon_30keV, Si, _30keV.log
optS, Silicon_40keV, Si, _40keV.log
optS, Silicon_50keV, Si, _50keV.log
)

