FNAME        = test37
getenv       = true
executable   = $ENV(G4BWORK)/$(FNAME)
ID           = $(ClusterId).$(ProcId)
output       = $(name1)_$(phys).$(ID).out
error        = $(name1)_$(phys).$(ID).err
log          = $(FNAME)_$(name1)_$(phys).$(ID).log
request_cpus = 1
requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour = "workday"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_remaps = "Sandia.out=$(name1)_$(phys)$(name2)"
arguments = $ENV(G4INSTALL)/tests/ctests_integration/$(FNAME)/$(argum).in

environment = "PHYSLIST=emstandard"
phys = opt0
queue argum, name1, name2 from (
Aluminum, Al, .log
Molybdenum, Mo, .log
Tantalum, Ta, .log
TaAl, TaAl, .log
AlAuAl, AlAuAl, .log
Beryllium, Be, .log
Uranium, U, .log
Silicon_15keV, Si, _15keV.log
Silicon_20keV, Si, _20keV.log
Silicon_30keV, Si, _30keV.log
Silicon_40keV, Si, _40keV.log
Silicon_50keV, Si, _50keV.log
)

environment = "PHYSLIST=emstandard_opt3"
phys = opt3
queue argum, name1, name2 from  (
Aluminum, Al, .log
Molybdenum, Mo, .log
Tantalum, Ta, .log
TaAl, TaAl, .log
AlAuAl, AlAuAl, .log
Beryllium, Be, .log
Uranium, U, .log
Silicon_15keV, Si, _15keV.log
Silicon_20keV, Si, _20keV.log
Silicon_30keV, Si, _30keV.log
Silicon_40keV, Si, _40keV.log
Silicon_50keV, Si, _50keV.log
)

environment = "PHYSLIST=emstandard_opt4"
phys = opt4
queue argum, name1, name2 from  (
Aluminum, Al, .log
Molybdenum, Mo, .log
Tantalum, Ta, .log
TaAl, TaAl, .log
AlAuAl, AlAuAl, .log
Beryllium, Be, .log
Uranium, U, .log
Silicon_15keV, Si, _15keV.log
Silicon_20keV, Si, _20keV.log
Silicon_30keV, Si, _30keV.log
Silicon_40keV, Si, _40keV.log
Silicon_50keV, Si, _50keV.log
)

environment = "PHYSLIST=emstandardWVI"
phys = optG
queue argum, name1, name2 from  (
Aluminum, Al, .log
Molybdenum, Mo, .log
Tantalum, Ta, .log
TaAl, TaAl, .log
AlAuAl, AlAuAl, .log
Beryllium, Be, .log
Uranium, U, .log
Silicon_15keV, Si, _15keV.log
Silicon_20keV, Si, _20keV.log
Silicon_30keV, Si, _30keV.log
Silicon_40keV, Si, _40keV.log
Silicon_50keV, Si, _50keV.log
)

environment = "PHYSLIST=emstandardSS"
phys = optS
queue argum, name1, name2 from  (
Aluminum, Al, .log
Molybdenum, Mo, .log
Tantalum, Ta, .log
TaAl, TaAl, .log
AlAuAl, AlAuAl, .log
Beryllium, Be, .log
Uranium, U, .log
Silicon_15keV, Si, _15keV.log
Silicon_20keV, Si, _20keV.log
Silicon_30keV, Si, _30keV.log
Silicon_40keV, Si, _40keV.log
Silicon_50keV, Si, _50keV.log
)
