#---Utility Macros----------------------------------------------------------
# - COMPILER
function(get_compiler_tag _output)
  if(DEFINED ENV{CC})
    set(compiler_cmd $ENV{CC})
  elseif(WIN32)
    find_program(compiler_cmd cl)
  else()
    find_program(compiler_cmd gcc)
  endif()

  if(compiler_cmd MATCHES cl.exe$)
    set(compiler vc)
    execute_process(COMMAND ${compiler_cmd} ERROR_VARIABLE versioninfo OUTPUT_VARIABLE out)
    string(REGEX REPLACE ".*Version ([0-9]+)[.].*" "\\1" cvers "${versioninfo}")
    if(cvers MATCHES 19)
      #  19.5z.xxx              is 145z  Studio 2026
      #  19.4z.xxx              is 144z  Studio 2022
      #  19.3z.xxx              is 143z  Studio 2022
      #  19.2z.xxx              is 142z  Studio 2019
       set(cvers 14)
      string(REGEX REPLACE ".*Version ([0-9]+)[.]([0-9]+)[.].*" "\\1\\2" cverslong "${versioninfo}")
      if(cverslong MATCHES 195)
        set(cvers 145)
      elseif(cverslong MATCHES 194)
        set(cvers 144)
      elseif(cverslong MATCHES 193)
        set(cvers 143)
      elseif(cverslong MATCHES 192)
        set(cvers 142)
      endif()  
    endif()    
  elseif(compiler_cmd MATCHES gcc[0-9]*$)
    set(compiler gcc)
    execute_process(COMMAND ${compiler_cmd} -dumpversion OUTPUT_VARIABLE GCC_VERSION)
    message(STATUS "g4macros.cmake: gcc compiler version ${GCC_VERSION}")
    string(REGEX MATCHALL "[0-9]+" GCC_VERSION_COMPONENTS ${GCC_VERSION})
    list(LENGTH GCC_VERSION_COMPONENTS GCC_VERSION_ELEMENTS)
    list(GET GCC_VERSION_COMPONENTS 0 GCC_MAJOR)
    if(GCC_VERSION_ELEMENTS GREATER_EQUAL 2)
      list(GET GCC_VERSION_COMPONENTS 1 GCC_MINOR)
      set(cvers ${GCC_MAJOR}${GCC_MINOR})
    else()
      set(cvers ${GCC_MAJOR})
    endif()  
  elseif(compiler_cmd MATCHES icc$)
    set(compiler icc)
    execute_process(COMMAND ${compiler_cmd} -dumpversion OUTPUT_VARIABLE ICC_VERSION)
    string(REGEX MATCHALL "[0-9]+" ICC_VERSION_COMPONENTS ${ICC_VERSION})
    list(GET ICC_VERSION_COMPONENTS 0 ICC_MAJOR)
    set(cvers ${ICC_MAJOR})
  elseif(compiler_cmd MATCHES icx$)
    set(compiler icx)
    execute_process(COMMAND ${compiler_cmd} -dumpversion OUTPUT_VARIABLE ICX_VERSION)
    string(REGEX MATCHALL "[0-9]+" ICX_VERSION_COMPONENTS ${ICX_VERSION})
    list(GET ICX_VERSION_COMPONENTS 0 ICX_MAJOR)
    set(cvers ${ICX_MAJOR})
  elseif(compiler_cmd MATCHES clang)
    set(compiler clang)
    set(compilerversion_cmd "${compiler_cmd} -dumpversion")
    separate_arguments(compilerversion_cmd)
    execute_process(COMMAND ${compilerversion_cmd} OUTPUT_VARIABLE CLANG_VERSION ERROR_VARIABLE CLANG_VERSION COMMAND_ECHO STDOUT )
    message(STATUS "g4macros.cmake: compiler_cmd ${compiler_cmd}") 
    message(STATUS "g4macros.cmake: clang version ${CLANG_VERSION}") 
    string(REGEX REPLACE "^([0-9]+)\\.[0-9].*$" "\\1" CLANG_MAJOR "${CLANG_VERSION}")
    string(REGEX REPLACE "^.[0-9]+\\.([0-9]).*$" "\\1" CLANG_MINOR "${CLANG_VERSION}")
    message(STATUS "g4macros.cmake: clang major ${CLANG_MAJOR}") 
    message(STATUS "g4macros.cmake: clang minor ${CLANG_MINOR}")    
    set(cvers ${CLANG_MAJOR}${CLANG_MINOR})
  else()
    set(compiler unk)
    set(cvers)
  endif()

  set(${_output} "${compiler}${cvers}" PARENT_SCOPE)
endfunction()

# - WINDOWS
function(get_windows_version _output)
  execute_process(COMMAND cmd /c ver OUTPUT_VARIABLE osvers)
  if(osvers MATCHES "Version 5")
    set(osvers xp)  
  elseif(osvers MATCHES "Version 6.1")
    set(osvers 7)
  elseif(osvers MATCHES "Version 6.2")
    set(osvers 8)
  elseif(osvers MATCHES "Version 6.3")
    #  8.1
    set(osvers 8)
  elseif(osvers MATCHES "Version 10.0.1")
    set(osvers 10)
  elseif(osvers MATCHES "Version 10.0.2")
    set(osvers 11)
  else()
    set(osvers unk)
  endif()

  set(${_output} "${osvers}" PARENT_SCOPE)
endfunction()

# LINUX
function(get_linux_version _distro _version)
  # FROM CMAKE 3.22 can use:
  # cmake_host_system_information(RESULT DISTRO QUERY DISTRIB_INFO)
  # foreach(VAR IN LISTS DISTRO)
  #   message(STATUS "${VAR}=`${${VAR}}`")
  # endforeach() 
  execute_process(COMMAND cat /etc/issue OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(issue MATCHES Ubuntu)
    set(os ubuntu)
    string(REGEX REPLACE ".*Ubuntu ([0-9]+)[.].*" "\\1" osvers "${issue}")
  elseif(issue MATCHES SLC)
    set(os slc)
    string(REGEX REPLACE ".*release ([0-9]+)[.].*" "\\1" osvers "${issue}")
  else()
    execute_process(COMMAND  lsb_release -d OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT issue)
      if(EXISTS /etc/os-release)
        execute_process(COMMAND grep PRETTY_NAME /etc/os-release OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
      endif()
    endif()
    if(issue MATCHES CentOS)
      set(os CentOS)
      execute_process(COMMAND  lsb_release -r OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
      if(issue)
        string(REGEX REPLACE "^Release:[ \t]*([0-9]+)[.].*" "\\1" osvers "${issue}")
      else()
        if(EXISTS /etc/os-release)
          execute_process(COMMAND grep VERSION_ID /etc/os-release OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
          string(REGEX REPLACE "^VERSION_ID=\"([0-9]+)\"" "\\1" osvers "${issue}")
          message(STATUS "g4macros.cmake: CentOS version ${osvers}")
        endif()
      endif()
    elseif(issue MATCHES AlmaLinux)
      set(os alma)
      if(EXISTS /etc/os-release)
        execute_process(COMMAND grep VERSION_ID /etc/os-release OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
        string(REGEX REPLACE "^VERSION_ID=\"([0-9]+)[.].*" "\\1" osvers "${issue}")
        message(STATUS "g4macros.cmake: Alma Linux version ${osvers}")
      endif()
    elseif(issue MATCHES "Red Hat Enterpris")
      set(os rhel)
      if(EXISTS /etc/os-release)
        execute_process(COMMAND grep VERSION_ID /etc/os-release OUTPUT_VARIABLE issue OUTPUT_STRIP_TRAILING_WHITESPACE)
        string(REGEX REPLACE "^VERSION_ID=\"([0-9]+)[.].*" "\\1" osvers "${issue}")
        message(STATUS "g4macros.cmake: Red Hat Enterprise Linux version ${osvers}")
      endif()
    else()
      set(os linux)
      set(osvers unknown)
      message(STATUS "g4macros.cmake: OS not configured: ${issue}.") 
    endif()
  endif() 

  set(${_distro} "${os}" PARENT_SCOPE)
  set(${_version} "${osvers}" PARENT_SCOPE)
endfunction()


function(get_configuration_tag tag)
  #---arch--------------
  cmake_host_system_information(RESULT arch QUERY OS_PLATFORM)
  # On Windows, need to consider `Platform` env var
  if(WIN32 AND DEFINED ENV{Platform})
    set(arch $ENV{Platform})
    string(TOLOWER ${arch} arch)
  endif()

  #---os----------------
  if(APPLE)
    set(os mac)
    cmake_host_system_information(RESULT osvers QUERY OS_RELEASE)
    # Only keep major version
    string(REGEX REPLACE "^([0-9]+)\\..*" "\\1" osvers "${osvers}")
  elseif(WIN32)
    set(os win)
    get_windows_version(osvers)
  else()
    # Assumed Linux...
    get_linux_version(os osvers)
  endif()

  #---compiler-----------
  get_compiler_tag(compiler)

  set(${tag} ${arch}-${os}${osvers}-${compiler}${cvers} PARENT_SCOPE)
  message(STATUS "g4macros.cmake: tag: ${tag}, os ${os}, osvers ${osvers}, compiler ${compiler}")    
endfunction()

function(get_pwd pwd)
  if(WIN32)
    execute_process(COMMAND cmd /c cd OUTPUT_VARIABLE p OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REPLACE "\\" "/" p ${p})
  else()
    set(p $ENV{PWD})
  endif()
  set(${pwd} ${p} PARENT_SCOPE)  
endfunction()
