//---------------------------------------
//        Macro file for test30
//         elastic scattering 
//---------------------------------------
#verbose
0
#events
10000
//--------Proton_processes
#particle
proton
#energy(MeV)
200.
//--------
#material
G4_C
#step(g/cm2)
2
#nbinsa
90
#thetamax
90
//--------
#generator
Elastic
#generator
ElasticDIFF
#generator
ElasticHE
//#generator
//ElasticLE
#generator
ElasticCHIPS
#exit

