# macro for rdecay01
#
/control/cout/ignoreThreadsExcept 0
/control/verbose 1
/run/verbose 1
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/gun/particle ion
/gun/ion 6 14
#
/tracking/verbose 2
/run/beamOn 1
/tracking/verbose 0
#
#
/analysis/setFileName C14_1
/analysis/h1/set 1  100  0. 200. keV	#e+ e-
/analysis/h1/set 2  100  0. 200. keV	#neutrino
/analysis/h1/set 6  100  0. 200. keV	#EkinTot (Q)
#
/run/printProgress 10000
/run/beamOn 100000
#
