# Verbose
#
/control/verbose 2
/tracking/verbose 2
/run/verbose 2

#/AXPET/gun/optPhotonPolar -360.0 deg
/gun/position 0.0 0.0 15.0 mm
#/run/beamOn 1
#/run/beamOn 1
#/run/beamOn 1
#if you want add Rotation to detector[deg]
#/mydet/RotateX 10.
#/mydet/RotateY 10.
#if you want abort Run instead of Warning Message
/mydet/AbortRun 1
#if you want to change the detector


/mydet/SelectDetector Shell
/run/beamOn 30
#/mydet/SelectDetector Ellipsoid
#/run/beamOn 30
#/mydet/SelectDetector Tubs
#/run/beamOn 30000
#/mydet/SelectDetector Cons
#/run/beamOn 3000
#/mydet/SelectDetector Polycone
#/run/beamOn 3000
#/mydet/SelectDetector Polyhedra
#/run/beamOn 3000
#/mydet/SelectDetector Para
#/run/beamOn 3000
#/mydet/SelectDetector Torus
#/run/beamOn 3000
#/mydet/SelectDetector Box
#/run/beamOn 3000
#/mydet/SelectDetector Orb
#/run/beamOn 3000
#/mydet/SelectDetector Trd
#/run/beamOn 3000
#/mydet/SelectDetector Trap
#/run/beamOn 3000

