# Verbose
#
/control/verbose 2
#/tracking/verbose 2
/run/verbose 2

# Create empty scene 
/vis/scene/create

#
/vis/open OGL 600x600-0+0

# Draw scene
/vis/viewer/zoom 1
#/vis/viewer/set/viewpointThetaPhi -50 -60 deg
/vis/viewer/set/viewpointThetaPhi 90 0 deg
#/vis/viewer/set/viewpointThetaPhi 105 165 deg

/vis/viewer/flush
#
# for drawing the tracks
# if too many tracks cause core dump => storeTrajectory 0
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#
#/testem/event/drawTracks all
/vis/scene/add/trajectories
