# New Geant4 macro for visulization, common for all tests
# By I. Hrivnacova, IPN Orsay; 25/01/2008

/tracking/verbose 1
/run/verbose 1
/run/initialize
/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/viewer/set/style surface
/fred/draw NORMAL
/tracking/storeTrajectory 1
/vis/drawVolume test
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
