# Macro file for test32 that defines files name
# Called from run-xxx.mac

# default file name
/analysis/setFileName default.{defaultOutput}

# extra files with a single object
/analysis/h1/setFileName 0 h1-{appendName}.csv
/analysis/h1/setFileName 1 h1-{appendName}.hdf5
/analysis/h1/setFileName 2 h1-{appendName}.root
/analysis/h1/setFileName 3 h1-{appendName}.xml
# ntuple
/analysis/ntuple/setFileName 0 n1.{defaultOutput}

# extra files with more objects
/analysis/h1/setFileName 4 histos-{appendName}.csv
/analysis/h1/setFileName 5 histos-{appendName}.hdf5
/analysis/h1/setFileName 6 histos-{appendName}.root
/analysis/h1/setFileName 7 histos-{appendName}.xml
#
/analysis/h2/setFileName 0 histos-{appendName}.csv
/analysis/h3/setFileName 0 histos-{appendName}.hdf5
/analysis/p1/setFileName 0 histos-{appendName}.root
/analysis/p2/setFileName 0 histos-{appendName}.xml
# ntuples
/analysis/ntuple/setFileName 1 ntuples.{defaultOutput}
/analysis/ntuple/setFileName 2 ntuples.{defaultOutput}
